apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook
  namespace: admissioner
webhooks:
  - name: admissioner.example.com
    failurePolicy: Fail
    clientConfig:
      service:
        name: admissioner
        namespace: admissioner
        path: /validate/deployments
      caBundle: <redacted> # Insert your CA
    rules:
      - apiGroups: ["apps"]
        resources:
          - "deployments"
        apiVersions:
          - "*"
        operations:
          - CREATE